/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author prach
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

     JPanel userProcessContainer;
    PersonDirectory personDirectory;
    /**
     * Creates new form CreatePersonJPanel
     */
    public CreatePersonJPanel(JPanel container,PersonDirectory directory) {
        initComponents();
        userProcessContainer=container;
        personDirectory=directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblfname = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        lbllname = new javax.swing.JLabel();
        lblWorkAddress = new javax.swing.JLabel();
        lblHStreetAddress = new javax.swing.JLabel();
        lblHUnitNumber = new javax.swing.JLabel();
        lblHCity = new javax.swing.JLabel();
        lblHState = new javax.swing.JLabel();
        lblHZipCode = new javax.swing.JLabel();
        lblHPhoneNumber = new javax.swing.JLabel();
        txtHStreetAddress = new javax.swing.JTextField();
        txtHUnitNumber = new javax.swing.JTextField();
        txtHCity = new javax.swing.JTextField();
        txtHState = new javax.swing.JTextField();
        txtHZipCode = new javax.swing.JTextField();
        txtHPhoneNumber = new javax.swing.JTextField();
        lblWPhoneNumber = new javax.swing.JLabel();
        txtWStreetAddress = new javax.swing.JTextField();
        txtWUnitNumber = new javax.swing.JTextField();
        txtWCity = new javax.swing.JTextField();
        txtWState = new javax.swing.JTextField();
        txtWZipCode = new javax.swing.JTextField();
        txtWPhoneNumber = new javax.swing.JTextField();
        lblWStreetAddress = new javax.swing.JLabel();
        lblWUnitNumber = new javax.swing.JLabel();
        lblWCity = new javax.swing.JLabel();
        lblWState = new javax.swing.JLabel();
        lblWZipCode = new javax.swing.JLabel();

        btnCreate.setBackground(new java.awt.Color(255, 153, 153));
        btnCreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreate.setText("Create ");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTitle.setText("Create Person");

        lblfname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblfname.setText("First Name");

        lblSSN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblSSN.setText("SSN");

        lblage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblage.setText("Age");

        lblHomeAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHomeAddress.setText("Home Address");

        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });

        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });

        lbllname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbllname.setText("Last Name");

        lblWorkAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblWorkAddress.setText("Work Address");

        lblHStreetAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHStreetAddress.setText("Street Adrdress");

        lblHUnitNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHUnitNumber.setText("Unit Number");

        lblHCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHCity.setText("City");

        lblHState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHState.setText("State");

        lblHZipCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHZipCode.setText("Zip Code");

        lblHPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHPhoneNumber.setText("Phone Number");

        txtHStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHStreetAddressActionPerformed(evt);
            }
        });

        lblWPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblWPhoneNumber.setText("Phone Number");

        txtWStreetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWStreetAddressActionPerformed(evt);
            }
        });

        txtWCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWCityActionPerformed(evt);
            }
        });

        lblWStreetAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblWStreetAddress.setText("Street Adrdress");

        lblWUnitNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblWUnitNumber.setText("Unit Number");

        lblWCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblWCity.setText("City");

        lblWState.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblWState.setText("State");

        lblWZipCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblWZipCode.setText("Zip Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(287, 287, 287)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHomeAddress)
                                .addComponent(lblHStreetAddress)
                                .addComponent(lblHUnitNumber)
                                .addComponent(lblHCity)
                                .addComponent(lblHState)
                                .addComponent(lblHZipCode)
                                .addComponent(lblHPhoneNumber)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSSN)
                                    .addComponent(lblfname)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHStreetAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHUnitNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(83, 83, 83)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHState)
                                        .addComponent(txtHZipCode)
                                        .addComponent(txtHPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(62, 62, 62)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbllname)
                                        .addComponent(lblage))
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblWorkAddress)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblWStreetAddress)
                                        .addComponent(lblWUnitNumber)
                                        .addComponent(lblWZipCode)
                                        .addComponent(lblWPhoneNumber)
                                        .addComponent(lblWState)
                                        .addComponent(lblWCity))
                                    .addGap(83, 83, 83)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtWStreetAddress)
                                            .addComponent(txtWUnitNumber)
                                            .addComponent(txtWState)
                                            .addComponent(txtWZipCode)
                                            .addComponent(txtWPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfname)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllname)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblage)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSSN)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeAddress)
                    .addComponent(lblWorkAddress))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHStreetAddress)
                    .addComponent(txtHStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWStreetAddress)
                    .addComponent(txtWStreetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHUnitNumber)
                    .addComponent(txtHUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWUnitNumber)
                    .addComponent(txtWUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHCity)
                    .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWCity)
                    .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHState)
                    .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWState)
                    .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHZipCode)
                    .addComponent(txtHZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWZipCode)
                    .addComponent(txtWZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHPhoneNumber)
                    .addComponent(txtHPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWPhoneNumber)
                    .addComponent(txtWPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        String fname=txtfname.getText();
        String lname=txtlname.getText();
        String ssn=txtSSN.getText();
        int Age;
        
        String homestreet=txtHStreetAddress.getText();
        String homeUN=txtHUnitNumber.getText();
        String homecity=txtHCity.getText();
        String homestate=txtHState.getText();
        String homezip=txtHZipCode.getText();
        Long homephone;
        String workstreet=txtWStreetAddress.getText();
        String workUN=txtWUnitNumber.getText();
        String workcity=txtWCity.getText();
        String workstate=txtWState.getText();
        String workzip=txtWZipCode.getText();
        Long workphone;
        
        
        
        if(lname.isBlank()||fname.isBlank()||ssn.isBlank()||homestreet.isBlank()||homecity.isBlank()||homestate.isBlank()||homecity.isBlank()||homezip.isBlank()||workstreet.isBlank()||workUN.isBlank()||homeUN.isBlank()||workcity.isBlank()||workstate.isBlank()||workzip.isBlank()){
            JOptionPane.showMessageDialog(this,"All fields are mandatory","Error",JOptionPane.ERROR_MESSAGE);
            return;
            
        }
        try{
            Age=Integer.parseInt(txtAge.getText());
             homephone=Long.parseLong(txtHPhoneNumber.getText());
            workphone=Long.parseLong(txtWPhoneNumber.getText());
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(this,"  Please check the Age input","Error",JOptionPane.WARNING_MESSAGE);
        return;
        }
        Person p=personDirectory.addPerson();
        Address homeAddress = new Address(homestreet, homeUN, homecity,homestate,homezip,homephone);
        Address workAddress = new Address(workstreet, workUN, workcity,workstate,workzip,workphone);
        p.setFirstName(fname);
        p.setLastName(lname);
        p.setSSN(ssn);
        p.setAge(Age);
        p.setHomeAddress(homeAddress);
        p.setWorkAddress(workAddress);
                
        JOptionPane.showMessageDialog(this," Person Successfully created","Error",JOptionPane.INFORMATION_MESSAGE);
        
        System.out.println(p.getFirstName());
        System.out.println(p.getAge());
        
       
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtHStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHStreetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHStreetAddressActionPerformed

    private void txtWStreetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWStreetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWStreetAddressActionPerformed

    private void txtWCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblHCity;
    private javax.swing.JLabel lblHPhoneNumber;
    private javax.swing.JLabel lblHState;
    private javax.swing.JLabel lblHStreetAddress;
    private javax.swing.JLabel lblHUnitNumber;
    private javax.swing.JLabel lblHZipCode;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWCity;
    private javax.swing.JLabel lblWPhoneNumber;
    private javax.swing.JLabel lblWState;
    private javax.swing.JLabel lblWStreetAddress;
    private javax.swing.JLabel lblWUnitNumber;
    private javax.swing.JLabel lblWZipCode;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lbllname;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtHCity;
    private javax.swing.JTextField txtHPhoneNumber;
    private javax.swing.JTextField txtHState;
    private javax.swing.JTextField txtHStreetAddress;
    private javax.swing.JTextField txtHUnitNumber;
    private javax.swing.JTextField txtHZipCode;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWCity;
    private javax.swing.JTextField txtWPhoneNumber;
    private javax.swing.JTextField txtWState;
    private javax.swing.JTextField txtWStreetAddress;
    private javax.swing.JTextField txtWUnitNumber;
    private javax.swing.JTextField txtWZipCode;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    // End of variables declaration//GEN-END:variables
}
