/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JSplitPane;
import model.Address;
import model.Person;
import model.PersonDirectory;
import ui.PersonManager.CreatePersonJPanel;
import ui.PersonManager.ManagePersonsJPanel;

/**
 *
 * @author prach
 */
public class MainJFrame extends javax.swing.JFrame {

    private PersonDirectory personDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.personDirectory=new PersonDirectory();
        generateDemoData();
        ManagePersonsJPanel panel=new ManagePersonsJPanel(userProcessContainer,personDirectory);
        userProcessContainer.add("ManageAccount Working",panel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnView = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.lightGray);

        btnView.setBackground(new java.awt.Color(255, 255, 204));
        btnView.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        btnView.setText("List Person");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(255, 255, 204));
        btnCreate.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        btnCreate.setText("Add Person");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );

        jSplitPane2.setLeftComponent(jPanel1);

        userProcessContainer.setBackground(new java.awt.Color(220, 220, 249));
        userProcessContainer.setForeground(new java.awt.Color(204, 204, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1422, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel panel=new CreatePersonJPanel(userProcessContainer,personDirectory);
        userProcessContainer.add("CreatePersonJpanel Working",panel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         ManagePersonsJPanel panel=new ManagePersonsJPanel(userProcessContainer,personDirectory);
        userProcessContainer.add("ManageAccount Working",panel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
private void generateDemoData(){
    Person newPerson=personDirectory.addPerson();
    newPerson.setFirstName("Prachi");
    newPerson.setLastName("Pradhan");
    newPerson.setSSN("445558642");
    newPerson.setAge(24);
    Address haddr1=new Address("tremont Street","901","Boston","MA","01210",4545511805l);
    newPerson.setHomeAddress(haddr1);
    Address waddr1=new Address("tremont Street","981","Boston","MA","01210",4545151154l);
    newPerson.setWorkAddress(waddr1);
    Person newPerson1=personDirectory.addPerson();
    newPerson1.setFirstName("Tushar");
    newPerson1.setLastName("Dete");
    newPerson1.setSSN("585965896");
    newPerson1.setAge(24);
    Address haddr2=new Address("bolyston Street","985","NYC","NY","01210",87459123545l);
    newPerson1.setHomeAddress(haddr2);
    Address waddr2=new Address("Brookline Street","951","NYC","NY","01210",48513958745l);
    newPerson1.setWorkAddress(waddr2);
    Person newPerson2=personDirectory.addPerson();
    newPerson2.setFirstName("Prathamesh");
    newPerson2.setLastName("Pradhan");
    newPerson2.setSSN("87459615");
    newPerson2.setAge(22);
    Address haddr3=new Address("Roxbury Street","859","San jose","california","01510",8459123445l);
    newPerson2.setHomeAddress(haddr3);
    Address waddr3=new Address("Bolyston Street","542","San Jose","California","06910",75945631545l);
    newPerson2.setWorkAddress(waddr3);
    Person newPerson3=personDirectory.addPerson();
    newPerson3.setFirstName("Sneha");
    newPerson3.setLastName("Indulkar");
    newPerson3.setSSN("85421395");
    newPerson3.setAge(24);
    Address haddr4=new Address("Alponso Street","745","dallas","texas","58745",78459654654l);
    newPerson3.setHomeAddress(haddr4);
    Address waddr4=new Address("tremont Street","754","dallas","texas","42658",4545151145l);
    newPerson3.setWorkAddress(waddr4);
    Person newPerson5=personDirectory.addPerson();
    newPerson5.setFirstName("Srushti");
    newPerson5.setLastName("Patil");
    newPerson5.setSSN("78459654");
    newPerson5.setAge(25);
    Address haddr5=new Address("Medford Street","122","Boston","MA","84556",7845931523l);
    newPerson5.setHomeAddress(haddr5);
    Address waddr5=new Address("Heath Street","855","Boston","MA","754125",4854593612l);
    newPerson5.setWorkAddress(waddr5);
    
    
}
}
